### ISSUE TITLE
Firefox에서 글자 위치가 이상하게 표시됩니다

### ISSUE THREAD

**Issue by usb9245** [junah201/solvedac-readme-stats#1]
![image](https://github.com/junah201/solvedac-readme-stats/assets/34123108/9e67f03a-3a3e-4994-af1f-3eae3ae3351e)
Windows 11 / Firefox Developer Edtion 117.0b3(좌), Microsoft Edge 115.0.1901.188(우)

**Comment by junah201** [comment]
```html
        <text x="25" y="76" fill="#ffffff" class = "info">
            Rating
        </text>
 ```
 다음과 같이 svg가 있을 때 안에 있는 글자를 `Rating`으로 해석하는게 아니라
 `      Rating`으로 앞에 공백이 붙어서 해석해서 생기는 문제인 것으로 확인했습니다.

**Comment by junah201** [comment]
![image](https://github.com/junah201/solvedac-readme-stats/assets/75025529/73775fe4-42b0-4fa9-b0cf-36086ae3c0f6)

FIreFox에서도 정상적으로 표시되는 것을 확인했습니다.
Github Readme에 표시되는 내용은 Github에서 자체적으로 이미지를 캐싱해서 저장하기 때문에 적용되기까지 최대 30분 정도의 시간이 소요될 수 있습니다.
Github Readme에도 정상적으로 표시되는 것을 확인하고, 이 이슈를 Close 하겠습니다.

@usb9245 이슈 감사합니다👍👍

**Comment by junah201** [comment]
![image](https://github.com/junah201/solvedac-readme-stats/assets/75025529/914aba28-bc2f-4f5d-8454-e3cb5c1cfa6a)

Github Readme에도 정상적으로 표시되는 것을 확인하였고, Close 하겠습니다.
감사합니다 !!
